name: Continuous deploy

on:
  push:
    branches: 
      - main
      - prod

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install serverless
        run: npm install -g serverless
      
      - name: Install npm
        run: npm install

      - name: Build Project
        env: 
          REACT_APP_API_URL: "${{ github.ref == 'refs/heads/main' && 'https://vkd8e5af0i.execute-api.ap-southeast-1.amazonaws.com/dev' || 'https://nwmxjrs4cb.execute-api.ap-south-1.amazonaws.com/prod' }}"
        run: npm run build

      - name: Deploy dev
        if: github.ref == 'refs/heads/main'
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.DEV_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DEV_AWS_SECRET_ACCESS_KEY}}
          BUCKET_NAME: dev-talent-board
          REGION: ap-southeast-1
          REACT_APP_API_URL: https://vkd8e5af0i.execute-api.ap-southeast-1.amazonaws.com/dev
        run: serverless --verbose

      - name: Deploy prod
        if: github.ref == 'refs/heads/prod'
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          # This should change as per your bucket name
          BUCKET_NAME: talent-awsug
          CDN_DISTRIBUTION_ID: ${{secrets.CDN_DISTRIBUTION_ID}}
          REACT_APP_API_URL: https://nwmxjrs4cb.execute-api.ap-south-1.amazonaws.com/prod
        run: |
          echo $REACT_APP_API_URL
          pip install awscli
          aws s3 cp ./build s3://$BUCKET_NAME/ --recursive --include "*"
          aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
          echo "Deployed to AWS UG talent website"